url: http://www.maisasolutions.com/
baseurl: ""

# Site settings
title: Web Development Services | Mobile Application Developers
pic: logo
email: your-email@domain.com
description: "Web and mobile development services. We offer ios native application, mobile apps, web development with ruby on rails, java, cloud computing and many more."
keywords: "ios mobile app development, web development services, mobile apps development, ruby on rails developers, mobile development services, mobile apps cloud computing, mobile application development, java web development services, ios development services, iOS Native Application Development"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d50032 #fed136
  secondary: d50032 #fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Pradeep Benjaram
  pic: 1
  position: Founder & M.D.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Niveditha Reddy
  pic: 2
  position: Director of Human Resources
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Prasanna Patil
  pic: 3
  position: Director of U.S. Ops
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/maisasolutions
  - title: facebook
    url: https://www.facebook.com/MaisaSolutions
  - title: stack-overflow
    url: https://github.com/maisaengineering/
  - title: bitbucket 
    url: https://github.com/maisaengineering/
  - title: github
    url: https://github.com/maisaengineering/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills , CA 90210

# Build settings
markdown: kramdown
permalink: pretty