url: maisalabs.com
baseurl: ""

# Site settings
title: Maisa Labs
email: contact@maisasolutions.com
description: "We build awesome things for the web & mobile. We’re creators, designers, engineers, educators and problem solvers. Let us build your awesome product..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty